export let Data = [
  {name: 'Abu Hail'},
  {name: 'Al Awir First'},
  {name: 'Al Awir Second'},
  {name: 'Al Bada'},
  {name: 'Al Baraha'},
  {name: 'Al Barsha First'},
  {name: 'Al Barsha Second'},
  {name: 'Al Barsha South First'},
  {name: 'Al Barsha South Second'},
  {name: 'Al Barsha South Third'},
  {name: 'Al Barsha Third'},
  {name: 'Al Buteen'},
  {name: 'Al Dhagaya'},
  {name: 'Al Garhoud'},
  {name: 'Al Guoz Fourth'},
  {name: 'Al Hamriya, Dubai'},
  {name: 'Al Hamriya Port'},
  {name: 'Al Hudaiba'},
  {name: 'Al Jaddaf'},
  {name: 'Al Jafiliya'},
  {name: 'Al Karama'},
  {name: 'Al Khabisi'},
  {name: 'Al Khwaneej First'},
  {name: 'Al Khwaneej Second'},
  {name: 'Al Kifaf'},
  {name: 'Al Mamzar'},
  {name: 'Al Manara'},
  {name: 'Al Merkad'},
  {name: 'Al Mina'},
  {name: 'Al Mizhar First'},
  {name: 'Al Mizhar Second'},
  {name: 'Al Muraqqabat'},
  {name: 'Al Murar'},
  {name: 'Al Sabkha'},
  {name: 'Al Muteena'},
  {name: 'Al Nahda First'},
  {name: 'Al Nahda Second'},
  {name: 'Al Quoz First'},
  {name: 'Al Quoz Industrial First'},
  {name: 'Al Quoz Industrial Fourth'},
  {name: 'Al Quoz Industrial Second'},
  {name: 'Al Quoz Industrial Third'},
  {name: 'Al Quoz Second'},
  {name: 'Al Quoz Third'},
  {name: 'Al Qusais First'},
  {name: 'Al Qusais Industrial Fifth'},
  {name: 'Al Qusais Industrial First'},
  {name: 'Al Qusais Industrial Fourth'},
  {name: 'Al Qusais Industrial Second'},
  {name: 'Al Qusais Industrial Third'},
  {name: 'Al Qusais Second'},
  {name: 'Al Qusais Third'},
  {name: 'Al Raffa'},
  {name: 'Al Ras'},
  {name: 'Al Rashidiya'},
  {name: 'Al Rigga'},
  {name: 'Al Safa First'},
  {name: 'Al Safa Second'},
  {name: 'Al Safouh First'},
  {name: 'Al Safouh Second'},
  {name: 'Al Satwa'},
  {name: 'Al Shindagha'},
  {name: 'Al Souq Al Kabeer'},
  {name: 'Al Twar First'},
  {name: 'Al Twar Second'},
  {name: 'Al Twar Third'},
  {name: "Al Warqa'a Fifth"},
  {name: "Al Warqa'a First"},
  {name: "Al Warqa'a Fourth"},
  {name: "Al Warqa'a Second"},
  {name: "Al Warqa'a Third"},
  {name: 'Al Wasl'},
  {name: 'Al Waheda'},
  {name: 'Ayal Nasir'},
  {name: 'Aleyas'},
  {name: 'Bu Kadra'},
  {name: 'Dubai Investment park First'},
  {name: 'Dubai Investment Park Second'},
  {name: 'Emirates Hill First'},
  {name: 'Emirates Hill Second'},
  {name: 'Emirates Hill Third'},
  {name: 'Hatta'},
  {name: 'Hor Al Anz'},
  {name: 'Hor Al Anz East'},
  {name: 'Jebel Ali 1'},
  {name: 'Jebel Ali 2'},
  {name: 'Jebel Ali Industrial'},
  {name: 'Jebel Ali Palm'},
  {name: 'Jumeira First'},
  {name: 'Palm Jumeira'},
  {name: 'Jumeira Second'},
  {name: 'Jumeira Third'},
  {name: 'Al Mankhool'},
  {name: 'Marsa Dubai'},
  {name: 'Mirdif'},
  {name: 'Muhaisanah Fourth'},
  {name: 'Muhaisanah Second'},
  {name: 'Muhaisanah Third'},
  {name: 'Muhaisnah First'},
  {name: 'Al Mushrif'},
  {name: 'Nad Al Hammar'},
  {name: 'Nadd Al Shiba Fourth'},
  {name: 'Nadd Al Shiba Second'},
  {name: 'Nadd Al Shiba Third'},
  {name: 'Nad Shamma'},
  {name: 'Naif'},
  {name: 'Al Muteena First'},
  {name: 'Al Muteena Second'},
  {name: 'Al Nasr, Dubai'},
  {name: 'Port Saeed'},
  {name: 'Arabian Ranches'},
  {name: 'Ras Al Khor'},
  {name: 'Ras Al Khor Industrial First'},
  {name: 'Ras Al Khor Industrial Second'},
  {name: 'Ras Al Khor Industrial Third'},
  {name: 'Rigga Al Buteen'},
  {name: 'Trade Centre 1'},
  {name: 'Trade Centre 2'},
  {name: 'Umm Al Sheif'},
  {name: 'Umm Hurair First'},
  {name: 'Umm Hurair Second'},
  {name: 'Umm Ramool'},
  {name: 'Umm Suqeim First'},
  {name: 'Umm Suqeim Second'},
  {name: 'Umm Suqeim Third'},
  {name: 'Wadi Alamardi'},
  {name: 'Warsan First'},
  {name: 'Warsan Second'},
  {name: "Za'abeel First"},
  {name: "Za'abeel Second"},
];


export let ServiceData = [
  {name: 'Cleaning'},
  {name: 'Car Painter'},
  {name: 'Deep Cleaning'},
  {name: 'Electrition'},
  {name: 'HandyMan'},
  {name: 'Paint Work'},
  {name: 'Plumbing'},
];